pipeline {
    agent {
        // Use the same workspace as the apply job
        customWorkspace '/var/lib/jenkins/workspace/Jenkins_vpc_dev'
    }

    stages {
        stage('Terraform Destroy') {
            steps {
                dir('terraform/dev') {
                    sh 'terraform init'
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}