pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Terraform Destroy') {
            steps {
                ws('/var/lib/jenkins/workspace/Jenkins-vpc-dev') {
                    dir('terraform/dev') {
                        sh 'terraform init'
                        sh 'terraform destroy -auto-approve'
                    }
                }
            }
        }
    }
}